[mypy]
# This addresses your specific note:
check_untyped_defs = True

# Useful for finding exactly where types are missing:
disallow_untyped_defs = False
warn_return_any = True
warn_unused_configs = True

# Since you use Django (oolog project), you might eventually 
# want to ignore missing imports for 3rd party libs:
ignore_missing_imports = True